#!/bin/bash
export LC_ALL=C

RANDOMSNORE=`echo 11.${RANDOM:0:3}`
snore()
{
  local IFS
  [[ -n "${_snore_fd:-}" ]] || exec {_snore_fd}<> <(:)
  read ${1:+-t "$1"} -u $_snore_fd || :
}

while killall -0 screen; do
  cut -d " " -f1-3 /proc/loadavg | sed 's/ /\//g'
  snore $RANDOMSNORE
done
